<?php

namespace MailerBundle\Repository;

use DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
    public function getJobs($jobStatus = null)
    {
        $qb = $this->createQueryBuilder('j')
            ->where('j.status = :activeStatus')
            ->setParameter('activeStatus', 1);

        switch($jobStatus){
            case ('featured'):
                $qb->andWhere('j.startedAt > :nowDate');
                break;
            case ('actual'):
                $qb->andWhere('j.startedAt < :nowDate');
                $qb->andWhere('j.endedAt is NULL');
                break;
            default:
                $qb->andWhere('j.endedAt < :nowDate');
        }

        $qb->setParameter('nowDate', new DateTime());

        return $qb->getQuery();

    }
}
