<?php

namespace MailerBundle\Repository;

use DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
    public function getJobs($ended = null)
    {
        $qb = $this->createQueryBuilder('j')
            ->where('j.status = :activeStatus')
            ->setParameter('activeStatus', 1);

        if($ended){
            $qb->andWhere('j.startedAt < :nowDate');
        }else{
            $qb->andWhere('j.startedAt > :nowDate');
        }
        $qb->setParameter('nowDate', new DateTime());

        return $qb->getQuery();

    }
}
