<?php

namespace MailerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository
{
    public function getActiveTemplates($templateAlias = null)
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.deleted = :deleted')
            ->setParameter('deleted', 0);

        if(!empty($templateAlias)){
            $qb->andWhere('t.alias = :alias')
                ->setParameter('alias', $templateAlias);
        }

        return $qb->getQuery();
    }

}
