MailerBundle\Entity\ContactList:
    type: entity
    table: null
    repositoryClass: MailerBundle\Repository\ContactListRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
#    oneToMany:
#        emails:
#            targetEntity: MailerBundle\Entity\Email
#            mappedBy: contact_list
    lifecycleCallbacks: {  }
