MailerBundle\Entity\Job:
    type: entity
    table: null
    repositoryClass: MailerBundle\Repository\JobRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        startedAt:
            type: datetime
            column: started_at
        endedAt:
            type: datetime
            column: ended_at
            nullable: true
        status:
            type: boolean
    manyToOne:
        template:
            targetEntity: MailerBundle\Entity\Template
            joinColunm:
                name: template_id
                referencedColumnName: id
        contact_list:
            targetEntity: MailerBundle\Entity\ContactList
            joinColumn:
                name: contact_list_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
