parameters:
    app.user_login.redirect.class: AppBundle\EventListener\LoginListener
#    ccdn_user_security.component.authentication.handler.logout_success_handler.class: CCDNUser\SecurityBundle\Component\Authentication\Handler\LogoutSuccessHandler

services:
    app.user_login.redirect:
        class: %app.user_login.redirect.class%
        public: false
        arguments: [@router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    app.user_registration.form.type:
        class: AppBundle\Form\UsersType
        tags:
            - { name: form.type, alias: app_user_registration }