AppBundle\Entity\Users:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UsersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToMany:
            groups:
                targetEntity: AppBundle\Entity\Groups
                joinTable:
                    name: User_Group
                    joinColumns:
                        user_id:
                            referencedColumnName: id
                    inverseJoinColumns:
                        group_id:
                            referencedColumnName: id
    lifecycleCallbacks: {  }