AppBundle\Entity\Users:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UsersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }