<?php

namespace MailerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateRepository extends EntityRepository
{
    public function getActiveTemplates($templateAlias = null, $max = null, $offset = null)
    {
        $qb = $this->createQueryBuilder('t')
            ->where('t.deleted = :deleted')
            ->setParameter('deleted', 1);

        if(!empty($max)){
            $qb->setMaxResults($max);
        }
        if(!empty($offset)){
            $qb->setFirstResult($offset);
        }

        if(!empty($templateAlias)){
            $qb->andWhere('t.alias = :alias')
                ->setParameter('alias', $templateAlias);
        }

        return $qb->getQuery();
        return $query->getResult();

    }

}
