mailer_template:
    resource: "@MailerBundle/Resources/config/routing/template.yml"
    prefix:   /template

job_template:
    resource: "@MailerBundle/Resources/config/routing/job.yml"
    prefix: /jobs

email_page_main:
    path: /emails/{page}
    defaults: { _controller: MailerBundle:Email:index, page: 1 }
    requirements:
        page: \d+

contact_list_template:
    resource: "@MailerBundle/Resources/config/routing/contact-list.yml"
    prefix: /contact-list