mailer_template:
    resource: "@MailerBundle/Resources/config/routing/template.yml"
    prefix:   /template

job_index_page:
    path:     /jobs/{jobs_type}/{page}
    defaults: { _controller: MailerBundle:Job:index,  jobs_type: actual, page: 1 }
    requirements:
        page: \d+
        jobs_type: actual|ended